/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author Elias
 */
public class VistaListines extends javax.swing.JInternalFrame {

    public JButton getBtnAprobar() {
        return btnAprobar;
    }

    public void setBtnAprobar(JButton btnAprobar) {
        this.btnAprobar = btnAprobar;
    }

    public JButton getBtnLimpiar() {
        return btnLimpiar;
    }

    public void setBtnLimpiar(JButton btnLimpiar) {
        this.btnLimpiar = btnLimpiar;
    }

    public JComboBox<String> getComboCedChofer() {
        return comboCedChofer;
    }

    public void setComboCedChofer(JComboBox<String> comboCedChofer) {
        this.comboCedChofer = comboCedChofer;
    }

    public JComboBox<String> getComboPlacaVehiculo() {
        return comboPlacaVehiculo;
    }

    public void setComboPlacaVehiculo(JComboBox<String> comboPlacaVehiculo) {
        this.comboPlacaVehiculo = comboPlacaVehiculo;
    }

    public JRadioButton getOpcA() {
        return opcA;
    }

    public void setOpcA(JRadioButton opcA) {
        this.opcA = opcA;
    }

    public JRadioButton getOpcB() {
        return opcB;
    }

    public void setOpcB(JRadioButton opcB) {
        this.opcB = opcB;
    }

    public JTextField getTxtCantPasajeros() {
        return txtCantPasajeros;
    }

    public void setTxtCantPasajeros(JTextField txtCantPasajeros) {
        this.txtCantPasajeros = txtCantPasajeros;
    }

    public JTextField getTxtCodigo() {
        return txtCodigo;
    }

    public void setTxtCodigo(JTextField txtCodigo) {
        this.txtCodigo = txtCodigo;
    }

    
    
    
    public VistaListines() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoTipo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblCantPasajeros = new javax.swing.JLabel();
        lblCedulaChofer = new javax.swing.JLabel();
        lblPlacaVehiculo = new javax.swing.JLabel();
        btnAprobar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        opcA = new javax.swing.JRadioButton();
        opcB = new javax.swing.JRadioButton();
        txtCantPasajeros = new javax.swing.JTextField();
        comboCedChofer = new javax.swing.JComboBox<>();
        comboPlacaVehiculo = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(158, 158, 158));

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblTitulo.setText("Listines");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(181, 181, 181))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 150, 136));
        jPanel3.setPreferredSize(new java.awt.Dimension(0, 6));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );

        lblCodigo.setText("Codigo:");

        lblTipo.setText("Tipo:");

        lblCantPasajeros.setText("Cant. Pasajeros:");

        lblCedulaChofer.setText("Cedula Chofer:");

        lblPlacaVehiculo.setText("Placa Vehiculo:");

        btnAprobar.setText("Aprobar");

        btnLimpiar.setText("Limpiar");

        grupoTipo.add(opcA);
        opcA.setText("A");

        grupoTipo.add(opcB);
        opcB.setText("B");

        comboCedChofer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));

        comboPlacaVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 484, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblCodigo)
                                    .addGap(105, 105, 105))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblTipo)
                                    .addGap(118, 118, 118)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCantPasajeros)
                                .addGap(61, 61, 61))
                            .addComponent(lblCedulaChofer)
                            .addComponent(lblPlacaVehiculo))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(opcA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(opcB))
                            .addComponent(txtCodigo)
                            .addComponent(txtCantPasajeros)
                            .addComponent(comboCedChofer, 0, 80, Short.MAX_VALUE)
                            .addComponent(comboPlacaVehiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btnAprobar)
                        .addGap(57, 57, 57)
                        .addComponent(btnLimpiar)))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(opcA)
                    .addComponent(opcB))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantPasajeros)
                    .addComponent(txtCantPasajeros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedulaChofer)
                    .addComponent(comboCedChofer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlacaVehiculo)
                    .addComponent(comboPlacaVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAprobar)
                    .addComponent(btnLimpiar))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAprobar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> comboCedChofer;
    private javax.swing.JComboBox<String> comboPlacaVehiculo;
    private javax.swing.ButtonGroup grupoTipo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblCantPasajeros;
    private javax.swing.JLabel lblCedulaChofer;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblPlacaVehiculo;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JRadioButton opcA;
    private javax.swing.JRadioButton opcB;
    private javax.swing.JTextField txtCantPasajeros;
    private javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables
}
